force-app/main/default/objects/Exam__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Exams</relationshipLabel>
    <relationshipName>Exams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exam__c/fields/Datetime_of_Exam__c.field-meta.xml
<CustomField>
    <fullName>Datetime_of_Exam__c</fullName>
    <label>Datetime of Exam</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exam</label>
    <referenceTo>Exam__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ExamAppController.cls
public with sharing class ExamAppController {
    @AuraEnabled(cacheable=true)
    public static List<Exam__c> getExamList(Id recordId) {
       
        return [SELECT Id,Name,Datetime_of_Exam__c,Total_Score__c  from Exam__c WHERE Contact__c=:recordId ];
    }
    //map which will contain ExamId and Question 
    @AuraEnabled(cacheable=true)
    public static List<Question__c> getQuestionList(Id examId) {
        return [SELECT id,Name,Exam__r.Name,Score__c  FROM Question__c WHERE Exam__c=:examId];
    }
}